import numpy as np
import argparse
import os


def parse_args():
    parser = argparse.ArgumentParser(description='Selecting HLA alignments from coverage stats generated by samtools depth -a -l length file.bam')
    parser.add_argument('-f', help='The coverage file generated by samtools',required=True, dest="coverage")
    parser.add_argument('-m', help='Minimal median coverage (NOT average/mean/whatever). Default is 5', required=False, dest="minMedian", default="5")
    return parser.parse_args()

args = parse_args()
statinfo = os.stat(args.coverage)
if statinfo.st_size > 0L:
    cover = np.loadtxt(args.coverage,usecols=[2])
    (mean, median, std, var) = np.mean(cover), np.median(cover),np.std(cover), np.var(cover)
    if median >= float(args.minMedian):
        print("%s\t%4.2f\t%4.2f\t%4.2f\t%4.2f") % (args.coverage.replace(".coverage",""), mean, median, std, var)

